// Selecciones frecuentes del Mundial con su bandera (emoji).
// Usado en el panel admin para autocompletar la bandera al cargar partidos.
export const TEAMS: { name: string; flag: string }[] = [
  { name: "Argentina", flag: "🇦🇷" },
  { name: "Brasil", flag: "🇧🇷" },
  { name: "Uruguay", flag: "🇺🇾" },
  { name: "Chile", flag: "🇨🇱" },
  { name: "Colombia", flag: "🇨🇴" },
  { name: "Ecuador", flag: "🇪🇨" },
  { name: "Paraguay", flag: "🇵🇾" },
  { name: "Perú", flag: "🇵🇪" },
  { name: "Bolivia", flag: "🇧🇴" },
  { name: "Venezuela", flag: "🇻🇪" },
  { name: "México", flag: "🇲🇽" },
  { name: "Estados Unidos", flag: "🇺🇸" },
  { name: "Canadá", flag: "🇨🇦" },
  { name: "Costa Rica", flag: "🇨🇷" },
  { name: "Panamá", flag: "🇵🇦" },
  { name: "Honduras", flag: "🇭🇳" },
  { name: "España", flag: "🇪🇸" },
  { name: "Francia", flag: "🇫🇷" },
  { name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { name: "Alemania", flag: "🇩🇪" },
  { name: "Italia", flag: "🇮🇹" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "Países Bajos", flag: "🇳🇱" },
  { name: "Bélgica", flag: "🇧🇪" },
  { name: "Croacia", flag: "🇭🇷" },
  { name: "Suiza", flag: "🇨🇭" },
  { name: "Dinamarca", flag: "🇩🇰" },
  { name: "Polonia", flag: "🇵🇱" },
  { name: "Austria", flag: "🇦🇹" },
  { name: "Serbia", flag: "🇷🇸" },
  { name: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { name: "Noruega", flag: "🇳🇴" },
  { name: "Marruecos", flag: "🇲🇦" },
  { name: "Senegal", flag: "🇸🇳" },
  { name: "Túnez", flag: "🇹🇳" },
  { name: "Egipto", flag: "🇪🇬" },
  { name: "Argelia", flag: "🇩🇿" },
  { name: "Ghana", flag: "🇬🇭" },
  { name: "Nigeria", flag: "🇳🇬" },
  { name: "Camerún", flag: "🇨🇲" },
  { name: "Costa de Marfil", flag: "🇨🇮" },
  { name: "Sudáfrica", flag: "🇿🇦" },
  { name: "Japón", flag: "🇯🇵" },
  { name: "Corea del Sur", flag: "🇰🇷" },
  { name: "Irán", flag: "🇮🇷" },
  { name: "Arabia Saudita", flag: "🇸🇦" },
  { name: "Australia", flag: "🇦🇺" },
  { name: "Catar", flag: "🇶🇦" },
  { name: "Por confirmar", flag: "🏳️" },
];

export function flagFor(name: string): string {
  return TEAMS.find((t) => t.name === name)?.flag ?? "🏳️";
}
